"""Bilingual copy for the negotiation engine (id / en)."""

ID = {
    "ctx": {
        "salary_raise": {
            "label": "Kenaikan Gaji / Promosi",
            "counterpart": "atasan dan HR",
            "unit": "gaji bulanan",
            "nonmon": [
                "Review kompensasi terjadwal dalam 3 bulan dengan kriteria tertulis",
                "Kenaikan level atau perubahan job title tanpa menunggu siklus tahunan",
                "Bonus retensi satu kali untuk menutup selisih angka",
                "Anggaran pelatihan atau sertifikasi profesional",
                "Pengaturan kerja fleksibel — dua hari remote per minggu",
            ],
        },
        "job_offer": {
            "label": "Offer Kerja Baru",
            "counterpart": "recruiter dan hiring manager",
            "unit": "gaji bulanan",
            "nonmon": [
                "Sign-on bonus untuk mengganti bonus yang hangus di tempat lama",
                "Review gaji dipercepat pada bulan keenam",
                "Level dan cakupan tanggung jawab yang lebih tinggi",
                "Tambahan cuti tahunan atau kebijakan kerja dari mana saja",
                "Anggaran perangkat, pelatihan, dan biaya relokasi",
            ],
        },
        "business_deal": {
            "label": "Deal Bisnis / Klien",
            "counterpart": "klien atau mitra",
            "unit": "nilai kontrak",
            "nonmon": [
                "Termin pembayaran di muka 50 persen",
                "Cakupan pekerjaan dikurangi dengan harga dipertahankan",
                "Kontrak jangka panjang dengan harga bertingkat",
                "Batas revisi yang jelas, revisi tambahan dikenakan biaya",
                "Studi kasus, testimoni, dan hak referensi sebagai nilai tambah",
            ],
        },
    },
    "timing": {
        "salary_raise": {
            "review_cycle_near": "Siklus review atau perencanaan anggaran kurang dari delapan minggu lagi",
            "recent_win": "Baru menyelesaikan hasil besar yang terlihat (kurang dari 60 hari)",
            "company_growing": "Perusahaan sedang tumbuh atau membukukan laba",
            "scope_increased": "Cakupan pekerjaan bertambah tanpa penyesuaian kompensasi",
            "hard_to_replace": "Posisi saya sulit dan mahal untuk digantikan",
            "competing_offer": "Ada peluang atau pembicaraan dengan perusahaan lain yang aktif",
            "hiring_freeze": "Perusahaan sedang membekukan rekrutmen atau melakukan efisiensi biaya",
            "recent_miss": "Baru saja ada kegagalan target yang terlihat oleh manajemen",
        },
        "job_offer": {
            "role_urgent": "Posisi ini sudah lama kosong atau harus segera diisi",
            "competing_offer": "Saya memegang offer lain yang masih aktif",
            "quarter_hiring_target": "Mereka mengejar target rekrutmen kuartal ini",
            "referral_champion": "Ada orang dalam yang mendukung saya secara aktif",
            "niche_skill": "Keahlian saya termasuk langka di pasar untuk peran ini",
            "budget_locked": "Anggaran gaji sudah terkunci dan sulit diubah",
            "already_resigned": "Saya sudah resign dan tidak punya posisi untuk kembali",
            "long_unemployed": "Saya sudah lebih dari tiga bulan tanpa pekerjaan",
        },
        "business_deal": {
            "client_deadline": "Klien terikat tenggat yang tidak bisa digeser",
            "inbound_lead": "Klien yang mendekati saya lebih dulu, bukan sebaliknya",
            "budget_cycle_open": "Anggaran klien baru dibuka untuk periode ini",
            "pipeline_full": "Kapasitas saya hampir penuh oleh pekerjaan lain",
            "unique_capability": "Kapabilitas yang saya tawarkan sulit ditemukan di tempat lain",
            "tender_price_war": "Prosesnya tender terbuka dengan persaingan harga",
            "cashflow_pressure": "Arus kas saya sedang tertekan dan butuh proyek ini",
            "client_shopping": "Klien sedang membandingkan banyak penawaran sekaligus",
        },
    },
    "tiers": {
        "dominant": {"label": "Posisi Dominan", "verdict": "Bukti dan alternatif Anda sama-sama kuat. Ajukan pertemuan pekan ini dan buka dengan angka anchor."},
        "strong": {"label": "Posisi Kuat", "verdict": "Anda siap bernegosiasi. Tutup satu hingga dua kesenjangan di bawah untuk memaksimalkan hasil."},
        "building": {"label": "Sedang Dibangun", "verdict": "Tahan dulu permintaan pertemuan. Jalankan rencana tindakan dua hingga empat pekan, lalu buka pembicaraan."},
        "weak": {"label": "Belum Siap", "verdict": "Membuka negosiasi sekarang berisiko ditolak, dan penolakan biasanya mengunci pembicaraan berikutnya selama enam bulan. Bangun bukti terlebih dahulu."},
    },
    "batna_tiers": {
        "none": "Tanpa Alternatif",
        "weak": "Alternatif Lemah",
        "moderate": "Alternatif Sedang",
        "strong": "Alternatif Kuat",
        "dominant": "Alternatif Dominan",
    },
    "impact_yes": "Dampak yang Anda dokumentasikan bernilai {ratio} kali biaya tahunan Anda. Ini mengubah percakapan menjadi soal pengembalian investasi, bukan soal permintaan.",
    "impact_no": "Dampak Anda belum berbentuk angka, sehingga argumen pengembalian investasi belum bisa dibangun. Inilah kesenjangan terbesar Anda saat ini.",
    "ladder": [
        {"label": "Anchor — angka pembuka", "note": "Sebutkan angka ini lebih dahulu. Jangan pernah menyebutnya sebagai batas minimum Anda."},
        {"label": "Target realistis", "note": "Titik di mana Anda menandatangani tanpa keraguan."},
        {"label": "Zona kompromi", "note": "Turun ke angka ini hanya jika ada imbalan: jadwal review, bonus, atau pengurangan cakupan."},
        {"label": "Batas bawah — walk away", "note": "Di bawah angka ini, alternatif terbaik Anda lebih menguntungkan. Hentikan negosiasi angka."},
    ],
    "market_pos": {"below": "berada di bawah pasar", "at": "sejajar dengan pasar", "above": "berada di atas median pasar"},
    "no_base": "Angka dasar belum diisi. Masukkan nilai saat ini atau angka penawaran agar sistem dapat menghitung posisi Anda.",
    "staged_plan": "Selisih terhadap harga pasar terlalu besar untuk ditutup dalam satu kali negosiasi. Gunakan pendekatan dua tahap: kunci {now} sekarang, disertai kesepakatan tertulis untuk meninjau ke {later} dalam enam hingga sembilan bulan dengan kriteria yang terukur.",
    "batna_note": "Alternatif terbaik Anda ({res}) sudah melampaui angka yang realistis diperoleh di meja ini. Ajukan {anchor} tanpa beban: bila ditolak, menjalankan alternatif itu memang keputusan yang lebih menguntungkan.",
    "levels": {"high": "tinggi", "medium": "sedang", "low": "rendah"},
    "gaps": {
        "P": {"pillar": "Performance", "problem": "Hasil kerja Anda belum berbentuk perbandingan angka sebelum dan sesudah.",
              "action": "Pilih dua metrik yang benar-benar Anda pengaruhi. Tuliskan angka awal, angka akhir, dan periodenya. Tanpa itu, kontribusi Anda terdengar sebagai pendapat.",
              "impact": "potensi +10 poin"},
        "A": {"pillar": "Achievement", "problem": "Pencapaian Anda belum diterjemahkan menjadi nilai uang atau risiko yang berhasil dihindari.",
              "action": "Untuk setiap pencapaian, jawab satu pertanyaan: berapa nilai yang dihasilkan atau dihemat? Estimasi dengan asumsi yang jelas jauh lebih kuat daripada kolom kosong.",
              "impact": "potensi +8 poin"},
        "C": {"pillar": "Comparison", "problem": "Anda belum memiliki pembanding pasar yang objektif.",
              "action": "Kumpulkan tiga sumber: data gaji publik, dua lowongan atau penawaran dengan cakupan setara, dan satu percakapan dengan orang di industri yang sama. Gunakan rentang, bukan satu angka tunggal.",
              "impact": "potensi +9 poin"},
        "T": {"pillar": "Timing", "problem": "Momen saat ini belum menjadi posisi terkuat Anda.",
              "action": "Tunda empat hingga delapan pekan. Kunci satu hasil besar terlebih dahulu, atau masuk pada jendela enam sampai delapan pekan sebelum siklus anggaran.",
              "impact": "potensi +6 poin"},
        "B": {"pillar": "BATNA", "problem": "Anda belum memiliki alternatif nyata, sehingga posisi Anda bergantung pada niat baik pihak lain.",
              "action": "Targetkan dua pekan: lima lamaran atau penawaran keluar, dan dua percakapan eksploratif. Alternatif tidak harus dijalankan; keberadaannya sudah mengubah cara Anda bernegosiasi.",
              "impact": "potensi +15 poin"},
    },
    "risks": {
        "no_zopa": {"title": "Zona kesepakatan belum terbentuk",
                    "detail": "Batas bawah Anda berada di atas kemampuan realistis pihak lain. Pilihannya: pindahkan negosiasi ke komponen non-uang, atau jalankan alternatif terbaik Anda."},
        "aggressive": {"title": "Anchor {pct} persen di atas dasar dengan bukti yang belum memadai",
                       "detail": "Angka besar tanpa dokumentasi dampak akan dibaca sebagai tidak realistis. Perkuat pilar Performance dan Achievement, atau turunkan anchor Anda."},
        "low_leverage": {"title": "Daya tawar masih rendah untuk membuka pembicaraan",
                         "detail": "Peluang ditolak besar, dan penolakan cenderung menutup pintu selama enam bulan. Jalankan rencana tindakan lebih dahulu."},
        "freeze": {"title": "Pihak lain sedang dalam mode efisiensi biaya",
                   "detail": "Alihkan fokus ke hal yang bisa dikunci tanpa kas: title, cakupan, dan komitmen review tertulis untuk kuartal berikutnya."},
        "relationship": {"title": "Alternatif kuat, namun hubungan tetap penting",
                         "detail": "Jangan gunakan alternatif sebagai ancaman. Bingkai seperti ini: \"Saya ingin melanjutkan di sini. Bantu saya membuat keputusan itu menjadi mudah.\""},
        "clear": {"title": "Tidak ada peringatan besar",
                  "detail": "Fokus pada eksekusi: latih pembukaan tiga kali dan siapkan jawaban untuk tiga bentuk penolakan yang paling mungkin."},
    },
    "script": {
        "opening": {
            "salary_raise": "Terima kasih untuk waktunya. Saya ingin membicarakan kompensasi untuk {role}. Saya sudah menyiapkan datanya agar diskusi ini berjalan objektif.",
            "job_offer": "Terima kasih atas penawarannya, saya sangat tertarik dengan peran {role} ini. Sebelum melanjutkan, saya ingin membicarakan paket kompensasinya secara terbuka.",
            "business_deal": "Terima kasih sudah mempertimbangkan proposal ini. Sebelum kita masuk ke angka, saya ingin memastikan nilai yang Anda terima dari pekerjaan {role} ini terlihat jelas.",
        },
        "perf_fallback": "hasil yang saya pegang membaik dibanding periode sebelumnya",
        "ach_fallback": "beberapa inisiatif di luar cakupan tugas formal saya",
        "body_perf": "Performance — {perf}.",
        "body_ach": "Achievement — {ach}.",
        "body_comp": "Comparison — untuk cakupan seperti ini, rentang pasar berada di sekitar {p50} sampai {p75}, sementara posisi saya saat ini {base}.",
        "body_time_review": "Timing — kita berada tepat sebelum siklus peninjauan, sehingga ini waktu yang paling tepat untuk membahasnya.",
        "body_time_default": "Timing — saya baru menyelesaikan satu siklus kerja penuh dengan hasil yang dapat dilihat.",
        "ask": "Berdasarkan hal-hal tersebut, angka yang saya ajukan adalah {anchor}. Saya terbuka mendiskusikan strukturnya, selama kita sepakat mengenai nilai kontribusinya.",
        "ask_nonum": "Berdasarkan hal-hal tersebut, saya ingin kita menyepakati angka yang mencerminkan kontribusi ini.",
        "silence": "Setelah menyebut angka, berhenti bicara. Diam selama lima detik. Biarkan pihak lain merespons lebih dulu — keheningan bekerja untuk pihak yang paling siap.",
        "closing": "Tutup dengan komitmen konkret: \"Boleh kita sepakati langkah berikutnya hari ini — siapa yang perlu menyetujui, dan kapan saya bisa menerima jawabannya?\" Kirim ringkasan tertulis dalam 24 jam.",
        "batna_obj": {
            "objection": "Mereka menunda tanpa memberi jawaban",
            "response": "Sampaikan alternatif Anda sebagai fakta, bukan ancaman: \"Saya sedang mempertimbangkan beberapa opsi, namun preferensi pertama saya tetap di sini. Saya membutuhkan kejelasan dalam {weeks} pekan ke depan.\"",
        },
        "objections": {
            "salary_raise": [
                {"objection": "\"Anggarannya tidak ada saat ini.\"",
                 "response": "\"Saya mengerti. Jika angka ini tidak memungkinkan sekarang, bisakah kita menyepakati kapan itu memungkinkan? Misalnya, review pada bulan ketiga dengan kriteria tertulis, atau sebagian selisih ditutup melalui bonus kinerja.\" Pindahkan pembicaraan dari ya atau tidak menjadi kapan dan bagaimana."},
                {"objection": "\"Angka Anda di atas struktur kami.\"",
                 "response": "\"Boleh saya mengetahui rentang untuk level ini? Jika saya sudah berada di batas atas, saya ingin memahami apa yang membuat seseorang naik level, sehingga kita membicarakan jalurnya, bukan hanya angkanya.\""},
                {"objection": "\"Rekan lain di posisi yang sama menerima angka serupa.\"",
                 "response": "\"Saya tidak membandingkan diri dengan rekan kerja. Saya membandingkan hasil saya dengan target, dan membandingkan cakupan pekerjaan ini dengan harga pasarnya.\""},
                {"objection": "\"Masa kerja Anda belum cukup lama.\"",
                 "response": "\"Saya sudah {tenure} bulan di sini, dan dalam periode itu {perf}. Saya memahami masa kerja menjadi pertimbangan. Usulan saya: sepakati angkanya sekarang dengan efektif bulan depan, atau tetapkan review terjadwal dengan kriteria yang jelas.\""},
            ],
            "job_offer": [
                {"objection": "\"Ini sudah angka terbaik kami.\"",
                 "response": "\"Saya menghargai keterbukaannya. Jika angka dasarnya benar-benar terkunci, bisakah kita bicara di komponen lain — sign-on bonus, review pada bulan keenam, atau tambahan cuti? Nilai totallah yang saya pertimbangkan.\""},
                {"objection": "\"Angka itu di atas rentang untuk level ini.\"",
                 "response": "\"Bisa saya pahami. Apakah memungkinkan menempatkan saya satu level di atas, mengingat cakupan yang akan saya pegang? Saya ingin kita menyelaraskan level dengan tanggung jawab, bukan sekadar menaikkan angka.\""},
                {"objection": "\"Berapa ekspektasi gaji Anda?\" (ditanyakan lebih dulu)\"",
                 "response": "\"Saya ingin memastikan cakupan perannya lebih dulu. Namun dari riset saya untuk peran serupa, rentangnya berada di sekitar {p50} sampai {p75}, dan saya nyaman berada di bagian atas rentang tersebut mengingat pengalaman saya.\" Sebutkan rentang, jangan satu angka."},
                {"objection": "\"Kami perlu jawaban Anda hari ini.\"",
                 "response": "\"Saya sangat serius dengan peran ini. Saya hanya butuh sedikit waktu untuk memutuskan dengan tenang — dua hari kerja. Keputusan yang diambil terburu-buru tidak menguntungkan kita berdua.\""},
            ],
            "business_deal": [
                {"objection": "\"Anggaran kami di bawah angka itu.\"",
                 "response": "\"Saya bisa menyesuaikan dengan anggaran Anda, dengan menyesuaikan cakupannya. Untuk angka tersebut, kita kerjakan bagian yang paling berdampak lebih dahulu, dan sisanya masuk fase kedua. Yang tidak saya lakukan adalah menurunkan kualitas pada harga yang lebih rendah.\""},
                {"objection": "\"Vendor lain menawarkan lebih murah.\"",
                 "response": "\"Kemungkinan besar benar. Perbandingan yang lebih berguna bukan harga, melainkan biaya keseluruhan: berapa lama sampai berjalan, berapa banyak revisi, dan berapa risiko harus dikerjakan ulang. Di tiga hal itulah selisih harga ini biasanya kembali.\""},
                {"objection": "\"Bisa diberi diskon untuk kerja sama pertama?\"",
                 "response": "\"Bisa, dengan imbalan yang setara: pembayaran di muka lebih besar, komitmen kontrak yang lebih panjang, atau izin menggunakan hasil kerja ini sebagai studi kasus. Diskon tanpa imbalan menetapkan harga acuan yang salah untuk kerja sama berikutnya.\""},
                {"objection": "\"Kami masih membandingkan beberapa penawaran.\"",
                 "response": "\"Wajar dan justru sehat. Agar perbandingannya adil, saya kirimkan rincian cakupan, asumsi, dan hal-hal yang tidak termasuk. Kapasitas saya untuk periode ini terbatas, jadi mohon informasikan keputusan Anda sebelum {weeks} pekan ke depan.\""},
            ],
        },
    },
    "checklist": [
        {"phase": "Data", "task": "Tuliskan dua sampai tiga metrik dengan format angka awal, angka akhir, dan periode"},
        {"phase": "Data", "task": "Terjemahkan minimal satu pencapaian menjadi nilai uang"},
        {"phase": "Data", "task": "Kumpulkan tiga sumber data pasar dan simpulkan sebagai rentang"},
        {"phase": "Posisi", "task": "Tetapkan anchor, target, dan batas bawah secara tertulis"},
        {"phase": "Posisi", "task": "Pastikan satu alternatif nyata sudah tersedia"},
        {"phase": "Eksekusi", "task": "Latih pembukaan tiga kali hingga tidak perlu membaca"},
        {"phase": "Eksekusi", "task": "Siapkan jawaban untuk tiga penolakan yang paling mungkin"},
        {"phase": "Eksekusi", "task": "Jadwalkan pertemuan khusus, jangan menyelipkannya di agenda rutin"},
        {"phase": "Tindak lanjut", "task": "Kirim ringkasan kesepakatan tertulis dalam 24 jam"},
    ],
}

EN = {
    "ctx": {
        "salary_raise": {
            "label": "Raise / Promotion",
            "counterpart": "your manager and HR",
            "unit": "monthly salary",
            "nonmon": [
                "A scheduled compensation review in three months with written criteria",
                "A level or title change without waiting for the annual cycle",
                "A one-off retention bonus to bridge the gap",
                "A training or professional certification budget",
                "Flexible arrangements — two remote days per week",
            ],
        },
        "job_offer": {
            "label": "New Job Offer",
            "counterpart": "the recruiter and hiring manager",
            "unit": "monthly salary",
            "nonmon": [
                "A sign-on bonus to replace the bonus you forfeit by leaving",
                "An accelerated salary review at month six",
                "A higher level and a wider scope of responsibility",
                "Additional annual leave or a work-from-anywhere policy",
                "Equipment, learning, and relocation budget",
            ],
        },
        "business_deal": {
            "label": "Business / Client Deal",
            "counterpart": "the client or partner",
            "unit": "contract value",
            "nonmon": [
                "Fifty percent payment upfront",
                "A reduced scope at the same price",
                "A longer contract with tiered pricing",
                "A clear revision limit, with extra revisions billed",
                "A case study, testimonial, and reference rights",
            ],
        },
    },
    "timing": {
        "salary_raise": {
            "review_cycle_near": "The review or budget planning cycle is less than eight weeks away",
            "recent_win": "I have just delivered a visible, significant result (within 60 days)",
            "company_growing": "The company is growing or profitable",
            "scope_increased": "My scope has expanded without a compensation adjustment",
            "hard_to_replace": "My role would be difficult and expensive to replace",
            "competing_offer": "I have an active opportunity or conversation elsewhere",
            "hiring_freeze": "The company is in a hiring freeze or cost-cutting mode",
            "recent_miss": "There has been a recent, visible missed target",
        },
        "job_offer": {
            "role_urgent": "The role has been open for a while or must be filled quickly",
            "competing_offer": "I hold another live offer",
            "quarter_hiring_target": "They are chasing a hiring target this quarter",
            "referral_champion": "Someone inside is actively advocating for me",
            "niche_skill": "My skill set is scarce for this kind of role",
            "budget_locked": "The salary budget is locked and hard to move",
            "already_resigned": "I have already resigned with no role to return to",
            "long_unemployed": "I have been out of work for more than three months",
        },
        "business_deal": {
            "client_deadline": "The client is bound to a deadline they cannot move",
            "inbound_lead": "The client approached me first, not the other way around",
            "budget_cycle_open": "Their budget has just opened for this period",
            "pipeline_full": "My capacity is nearly full with other work",
            "unique_capability": "What I offer is hard to source elsewhere",
            "tender_price_war": "This is an open tender competing mainly on price",
            "cashflow_pressure": "My cash flow is tight and I need this project",
            "client_shopping": "The client is comparing several proposals at once",
        },
    },
    "tiers": {
        "dominant": {"label": "Dominant Position", "verdict": "Your evidence and your alternatives are both strong. Request the meeting this week and open with your anchor."},
        "strong": {"label": "Strong Position", "verdict": "You are ready to negotiate. Close one or two of the gaps below to maximise the outcome."},
        "building": {"label": "Still Building", "verdict": "Hold off on the meeting request. Run the two to four week action plan first, then open the conversation."},
        "weak": {"label": "Not Ready Yet", "verdict": "Opening now risks a refusal, and a refusal usually locks the conversation for six months. Build the evidence first."},
    },
    "batna_tiers": {
        "none": "No Alternative",
        "weak": "Weak Alternative",
        "moderate": "Moderate Alternative",
        "strong": "Strong Alternative",
        "dominant": "Dominant Alternative",
    },
    "impact_yes": "The impact you documented is worth {ratio} times your annual cost. That reframes the conversation as a return on investment rather than a request.",
    "impact_no": "Your impact has no numbers attached yet, so the return-on-investment argument cannot be built. This is your largest gap.",
    "ladder": [
        {"label": "Anchor — your opening number", "note": "Say this number first. Never describe it as your minimum."},
        {"label": "Realistic target", "note": "The point at which you sign without hesitation."},
        {"label": "Compromise zone", "note": "Move here only in exchange for something: a review date, a bonus, or reduced scope."},
        {"label": "Walk-away point", "note": "Below this number your best alternative pays more. Stop negotiating on price."},
    ],
    "market_pos": {"below": "sits below the market", "at": "sits in line with the market", "above": "sits above the market median"},
    "no_base": "No base number yet. Enter your current value or the offer on the table so the engine can position you.",
    "staged_plan": "The gap to market is too wide to close in a single conversation. Use a two-stage approach: lock in {now} now, together with a written agreement to review towards {later} within six to nine months against measurable criteria.",
    "batna_note": "Your best alternative ({res}) already exceeds what is realistically available at this table. Ask for {anchor} without anxiety: if they decline, walking is genuinely the better decision.",
    "levels": {"high": "high", "medium": "medium", "low": "low"},
    "gaps": {
        "P": {"pillar": "Performance", "problem": "Your work has not been expressed as a before-and-after number.",
              "action": "Pick two metrics you genuinely influence. Write down the starting figure, the ending figure, and the period. Without them, your contribution reads as opinion.",
              "impact": "+10 points available"},
        "A": {"pillar": "Achievement", "problem": "Your achievements have not been translated into money earned, money saved, or risk avoided.",
              "action": "For each achievement answer one question: what did it generate or save? A clearly stated estimate is far stronger than an empty field.",
              "impact": "+8 points available"},
        "C": {"pillar": "Comparison", "problem": "You have no objective market benchmark yet.",
              "action": "Collect three sources: public salary data, two postings or quotes with comparable scope, and one conversation with someone in the same industry. Present a range, never a single figure.",
              "impact": "+9 points available"},
        "T": {"pillar": "Timing", "problem": "This moment is not your strongest one.",
              "action": "Delay four to eight weeks. Lock in one significant result first, or enter the six to eight week window before the budget cycle.",
              "impact": "+6 points available"},
        "B": {"pillar": "BATNA", "problem": "You have no real alternative, so your position depends on the other side's goodwill.",
              "action": "Set a two-week target: five applications or proposals out, and two exploratory conversations. You never have to use an alternative; simply having one changes how you negotiate.",
              "impact": "+15 points available"},
    },
    "risks": {
        "no_zopa": {"title": "No zone of possible agreement",
                    "detail": "Your walk-away point sits above what the other side can realistically pay. Either move the negotiation to non-monetary terms, or execute your best alternative."},
        "aggressive": {"title": "Anchor {pct} percent above base with thin evidence",
                       "detail": "A large number without documented impact reads as unrealistic. Strengthen Performance and Achievement, or lower the anchor."},
        "low_leverage": {"title": "Leverage is still too low to open",
                         "detail": "The odds of refusal are high, and a refusal tends to close the door for six months. Work the action plan first."},
        "freeze": {"title": "The other side is in cost-control mode",
                   "detail": "Shift focus to what can be locked in without cash: title, scope, and a written commitment to review next quarter."},
        "relationship": {"title": "Strong alternative, but the relationship matters",
                         "detail": "Never use your alternative as a threat. Frame it this way: \"I want to stay. Help me make that the easy decision.\""},
        "clear": {"title": "No major warnings",
                  "detail": "Focus on execution: rehearse your opening three times and prepare answers to the three most likely objections."},
    },
    "script": {
        "opening": {
            "salary_raise": "Thank you for the time. I would like to discuss compensation for {role}. I have prepared the data so we can keep this objective.",
            "job_offer": "Thank you for the offer — I am genuinely excited about the {role} role. Before we go further, I would like to discuss the package openly.",
            "business_deal": "Thank you for considering the proposal. Before we talk numbers, I want to make sure the value you receive from this {role} engagement is clear.",
        },
        "perf_fallback": "the results I own have improved against the previous period",
        "ach_fallback": "several initiatives beyond my formal remit",
        "body_perf": "Performance — {perf}.",
        "body_ach": "Achievement — {ach}.",
        "body_comp": "Comparison — for this scope the market range sits between {p50} and {p75}, while my current position is {base}.",
        "body_time_review": "Timing — we are right before the review cycle, which makes this the most useful moment to discuss it.",
        "body_time_default": "Timing — I have just completed a full delivery cycle with results you can see.",
        "ask": "On that basis, the number I am proposing is {anchor}. I am open on structure, as long as we agree on the value of the contribution.",
        "ask_nonum": "On that basis, I would like us to agree on a number that reflects this contribution.",
        "silence": "After you say the number, stop talking. Hold five seconds of silence. Let them respond first — silence favours the better-prepared party.",
        "closing": "Close with a concrete commitment: \"Can we agree the next step today — who needs to approve this, and when can I expect an answer?\" Send a written summary within 24 hours.",
        "batna_obj": {
            "objection": "They stall without giving an answer",
            "response": "State your alternative as a fact, not a threat: \"I am weighing a few options, but my first preference is here. I do need clarity within the next {weeks} weeks.\"",
        },
        "objections": {
            "salary_raise": [
                {"objection": "\"There is no budget right now.\"",
                 "response": "\"Understood. If the number is not possible now, can we agree when it becomes possible? For example, a review at month three against written criteria, or part of the gap closed through a performance bonus.\" Move the conversation from yes-or-no to when-and-how."},
                {"objection": "\"Your number is above our structure.\"",
                 "response": "\"Could you share the range for this level? If I am already at the top of it, I would like to understand what moves someone to the next level, so we discuss the path rather than only the figure.\""},
                {"objection": "\"Others in the same role are paid similarly.\"",
                 "response": "\"I am not comparing myself to colleagues. I am comparing my results against the target, and this scope against its market price.\""},
                {"objection": "\"You have not been here long enough.\"",
                 "response": "\"I have been here {tenure} months, and in that period {perf}. I understand tenure is a factor. My proposal: agree the number now effective next month, or set a scheduled review with explicit criteria.\""},
            ],
            "job_offer": [
                {"objection": "\"This is already our best number.\"",
                 "response": "\"I appreciate the candour. If base is genuinely fixed, could we look at the other components — a sign-on bonus, a review at month six, or additional leave? I am evaluating the total package.\""},
                {"objection": "\"That is above the band for this level.\"",
                 "response": "\"That makes sense. Given the scope I would be carrying, is placing me one level higher an option? I would rather align level with responsibility than simply push the number.\""},
                {"objection": "\"What are your salary expectations?\" (asked first)",
                 "response": "\"I would like to confirm the scope first. From my research on comparable roles, the range sits between {p50} and {p75}, and given my experience I would expect to be in the upper part of that range.\" Give a range, never a single number."},
                {"objection": "\"We need your answer today.\"",
                 "response": "\"I am serious about this role. I only need a little room to decide properly — two business days. A rushed decision serves neither of us.\""},
            ],
            "business_deal": [
                {"objection": "\"Our budget is below that number.\"",
                 "response": "\"I can work to your budget by adjusting scope. At that figure we deliver the highest-impact part first, and the remainder becomes phase two. What I will not do is reduce quality at a lower price.\""},
                {"objection": "\"Another vendor quoted less.\"",
                 "response": "\"Very likely true. The more useful comparison is not price but total cost: how long until it works, how many revision rounds, and the risk of rework. That is usually where this difference is recovered.\""},
                {"objection": "\"Can we get a discount on the first engagement?\"",
                 "response": "\"Yes, in exchange for something of equal value: a larger upfront payment, a longer commitment, or permission to use the work as a case study. A discount for nothing sets the wrong reference price for everything that follows.\""},
                {"objection": "\"We are still comparing proposals.\"",
                 "response": "\"That is reasonable and healthy. To make the comparison fair, I will send the scope, the assumptions, and what is explicitly excluded. My capacity for this period is limited, so please let me know within {weeks} weeks.\""},
            ],
        },
    },
    "checklist": [
        {"phase": "Data", "task": "Write two or three metrics as starting figure, ending figure, and period"},
        {"phase": "Data", "task": "Translate at least one achievement into a monetary value"},
        {"phase": "Data", "task": "Collect three market sources and express them as a range"},
        {"phase": "Position", "task": "Write down your anchor, target, and walk-away point"},
        {"phase": "Position", "task": "Make sure one real alternative is in place"},
        {"phase": "Execution", "task": "Rehearse the opening three times until you no longer read it"},
        {"phase": "Execution", "task": "Prepare answers to the three most likely objections"},
        {"phase": "Execution", "task": "Book a dedicated meeting; never slip this into a routine agenda"},
        {"phase": "Follow-up", "task": "Send a written summary of what was agreed within 24 hours"},
    ],
}

TEXTS = {"id": ID, "en": EN}


def t(lang: str):
    return TEXTS.get(lang, ID)
